spring:
  profiles:
    # init либо manual
    active: init
files:
  download:
    path: home/alexuglin/Downloads/apps/
    name: saved-contacts.txt
  upload:
    path: resources/
    name: default-contacts.txt